addons:
		sonarcloud:
				organization:	"Epelde3"
				token: "2bc16381395a40724ea65617de7ce2dc9948a212"	
script:
		#	the	following	command	line	builds	the	project,	runs	the	tests	with	coverage
		# and	then	execute	the	SonarCloud	analysis
 - mvn -X clean	org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacocomaven-plugin:report	 install	sonar:sonar