addons:
  sonarcloud:
    organization: "jononekin"
    token: "7aa69b260afe89bbb0dc2a3310cdd0cb5e392482" #encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysiss
  - mvn -X clean org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacoco-maven-plugin:report install sonar:sonar 